// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class balcao
{
    public int balcaoId { get; set; }

    public string balcaoDesignacao { get; set; }

    public virtual ICollection<senha> senha { get; } = new List<senha>();
}