// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class cae
{
    public int caeId { get; set; }

    public string caeCodigo { get; set; }

    public string caeNome { get; set; }

    public virtual ICollection<cliente> cliente { get; } = new List<cliente>();
}