// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class codpostal
{
    public int codpostalId { get; set; }

    public int distrito_Id { get; set; }

    public int concelho_Numero { get; set; }

    public string concelho_Codigo { get; set; }

    public int concelho_Id { get; set; }

    public virtual ICollection<cliente> cliente { get; } = new List<cliente>();

    public virtual concelho concelho { get; set; }

    public virtual distrito distrito { get; set; }
}