// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class concelho
{
    public int concelhoId { get; set; }

    public string concelhoNome { get; set; }

    public string concelhoCodigo { get; set; }

    public int concelhoNumero { get; set; }

    public int distrito_Id { get; set; }

    public int? regiao_Id { get; set; }

    public virtual ICollection<cliente> cliente { get; } = new List<cliente>();

    public virtual ICollection<codpostal> codpostal { get; } = new List<codpostal>();

    public virtual distrito distrito { get; set; }
}