// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class contactocliente
{
    public int contactoId { get; set; }

    public int? contactotipo_Id { get; set; }

    public string contactoPessoa { get; set; }

    public string contactoRegisto { get; set; }

    public int? cliente_Id { get; set; }

    public virtual cliente cliente { get; set; }

    public virtual contactotipo contactotipo { get; set; }
}