// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class dimensao
{
    public int dimensaoId { get; set; }

    public string dimensaoNome { get; set; }

    public virtual ICollection<cliente> cliente { get; } = new List<cliente>();
}