// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class distrito
{
    public int distritoId { get; set; }

    public string distritoNome { get; set; }

    public virtual ICollection<cliente> cliente { get; } = new List<cliente>();

    public virtual ICollection<codpostal> codpostal { get; } = new List<codpostal>();

    public virtual ICollection<concelho> concelho { get; } = new List<concelho>();
}