// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class estadoprojeto
{
    public int estadoprojetoId { get; set; }

    public string estadoprojetoNome { get; set; }

    public virtual ICollection<projeto> projeto { get; } = new List<projeto>();
}