// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class etiquetas
{
    public int etiquetaId { get; set; }

    public string ediquetaNome { get; set; }
}