// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class medida
{
    public int medidaId { get; set; }

    public string medidaNome { get; set; }

    public string medidaPrograma { get; set; }

    public virtual ICollection<projeto> projeto { get; } = new List<projeto>();
}