// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class projetoresumo
{
    public int projetoresumoId { get; set; }

    public DateTime? projetoresumoData { get; set; }

    public string projetoresumoDescricao { get; set; }

    public DateTime projetoresumoDatahoraregisto { get; set; }

    public int projeto_Id { get; set; }

    public int utilizador_Id_Criador { get; set; }

    public virtual projeto projeto { get; set; }

    public virtual utilizador utilizador_Id_CriadorNavigation { get; set; }
}