// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class projetofaturacao
{
    public int projetofaturacaoId { get; set; }

    public decimal? projetofaturacaoValorprevisto { get; set; }

    public decimal? projetofaturacaoFaturavalor { get; set; }

    public DateTime? projetofaturacaoFaturadata { get; set; }

    public decimal? projetofaturacaoRecibovalor { get; set; }

    public DateTime? projetofaturacaoRecibodata { get; set; }

    public int projeto_Id { get; set; }

    public virtual projeto projeto { get; set; }
}