// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class projeto
{
    public int projetoId { get; set; }

    public string projetoCodigo { get; set; }

    public string projetoNumero { get; set; }

    public string projetoDesignacao { get; set; }

    public string projetoAviso { get; set; }

    public decimal? projetoValorapresentado { get; set; }

    public decimal? projetoValoraprovado { get; set; }

    public decimal? projetoIncentivoaprovado { get; set; }

    public decimal? projetoValorrealizado { get; set; }

    public decimal? projetoIncentivorecebido { get; set; }

    public DateTime? projetoDatasubmissao { get; set; }

    public DateTime? projetoDatadecisao { get; set; }

    public DateTime? projetoDatacontratacao { get; set; }

    public DateTime? projetoDatainicio { get; set; }

    public DateTime? projetoDatafim { get; set; }

    public int? utilizador_ResponsavelId { get; set; }

    public int? utilizador_ApoioId { get; set; }

    public string projetoNotas { get; set; }

    public int? cliente_Id { get; set; }

    public int? medida_Id { get; set; }

    public int? estado_Id { get; set; }

    public bool projetoEpessoal { get; set; }

    public virtual ICollection<chat> chat { get; } = new List<chat>();

    public virtual cliente cliente { get; set; }

    public virtual estadoprojeto estado { get; set; }

    public virtual medida medida { get; set; }

    public virtual ICollection<projetofaturacao> projetofaturacao { get; } = new List<projetofaturacao>();

    public virtual ICollection<projetopedido> projetopedido { get; } = new List<projetopedido>();

    public virtual ICollection<projetoresumo> projetoresumo { get; } = new List<projetoresumo>();

    public virtual utilizador utilizador_Responsavel { get; set; }
}