// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class senha
{
    public int senhaId { get; set; }

    public string senhaUtilizador { get; set; }

    public string senhaSenha { get; set; }

    public int? cliente_Id { get; set; }

    public int balcao_Id { get; set; }

    public virtual balcao balcao { get; set; }
}