// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class tarefa
{
    public int tarefaId { get; set; }

    public int tarefaParentid { get; set; }

    public int projeto_Id { get; set; }

    public string tarefaNome { get; set; }

    public DateTime tarefaDatahoraregisto { get; set; }

    public DateTime tarefaDatalimite { get; set; }

    public int utilizador_Id { get; set; }

    public bool tarefaEstado { get; set; }

    public bool tarefaTemfilho { get; set; }

    public int tarefaPosicao { get; set; }

    public int? etiqueta_Id { get; set; }

    public string tarefaDescricao { get; set; }

    public virtual ICollection<chat> chat { get; } = new List<chat>();
}