// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class utilizador
{
    public int utilizadorId { get; set; }

    public string utilizadorEmail { get; set; }

    public string utilizadorIniciais { get; set; }

    public string utilizadorNome { get; set; }

    public string utilizadorPicture { get; set; }

    public virtual ICollection<projeto> projeto { get; } = new List<projeto>();

    public virtual ICollection<projetoresumo> projetoresumo { get; } = new List<projetoresumo>();
}