// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class vcliente
{
    public int clienteId { get; set; }

    public string clienteErpid { get; set; }

    public string clienteNipc { get; set; }

    public string clienteNome { get; set; }

    public string dimensaoNome { get; set; }

    public string regiaoNome { get; set; }

    public string distritoNome { get; set; }

    public string concelhoNome { get; set; }

    public string clienteEmail { get; set; }

    public string clienteTelefone { get; set; }

    public string setorNome { get; set; }

    public string caeNome { get; set; }
}