// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADNCORE_MUD.Shared.Models;

public partial class vlistagemprojetos
{
    public int projetoId { get; set; }

    public string clienteNome { get; set; }

    public string medidaNome { get; set; }

    public string projetoNumero { get; set; }

    public string vlistagemprojetosConcatenado { get; set; }
}